# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Dynamic programming for optimal segmentation
#'
#' Dynamic programming for changepoint detection of a givens sequence of data with up to N_segments
#'
#' @param data_vec numeric data vector, [N_data]
#' @param N_segments number of max segments
#'
#' @return loss_mat, loss matrix [N_data] x [N_segments]
#' @useDynLib CS599Changepoint, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @export
#' 
#' @examples
#' data(neuroblastoma, package="neuroblastoma")
#' library(data.table)
#' nb.dt <- data.table(neuroblastoma$profiles)
#' data.dt <- nb.dt[profile.id=="1" & chromosome=="1"]
#' DYNPROG_interface(data.dt$logratio,3)
DYNPROG_interface <- function(data_vec, N_segments) {
    .Call(`_CS599Changepoint_DYNPROG_interface`, data_vec, N_segments)
}

